using System;

namespace Quantra.DAL.Models
{
    /// <summary>
    /// POCO class for tracking prediction timing information throughout the prediction lifecycle.
    /// Captures timestamps at various stages to enable performance analysis and latency tracking.
    /// </summary>
    public class PredictionTimestamp
    {
        /// <summary>
        /// Gets or sets the timestamp when the prediction request was initiated.
        /// </summary>
        public DateTime RequestInitiated { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the Python ML model started inference.
        /// </summary>
        public DateTime? PythonInferenceStarted { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the Python ML model completed inference and returned results.
        /// This is the primary timestamp indicating when the prediction was generated by Python.
        /// </summary>
        public DateTime PythonInferenceCompleted { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the prediction result was received in C# code.
        /// </summary>
        public DateTime? ResultReceivedInCSharp { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the prediction was cached (if applicable).
        /// </summary>
        public DateTime? PredictionCached { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the prediction was retrieved from cache (if applicable).
        /// </summary>
        public DateTime? RetrievedFromCache { get; set; }

        /// <summary>
        /// Gets or sets the total inference time in milliseconds (Python execution time).
        /// </summary>
        public double InferenceTimeMs { get; set; }

        /// <summary>
        /// Gets or sets the total roundtrip time in milliseconds from request to result.
        /// </summary>
        public double TotalRoundtripTimeMs { get; set; }

        /// <summary>
        /// Gets or sets the symbol associated with this prediction.
        /// </summary>
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or sets the model type used for the prediction.
        /// </summary>
        public string ModelType { get; set; }

        /// <summary>
        /// Gets or sets the request ID for tracking and correlation.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or sets whether this prediction was retrieved from cache.
        /// </summary>
        public bool WasCached { get; set; }

        /// <summary>
        /// Gets the age of the prediction (time since Python inference completed).
        /// </summary>
        public TimeSpan Age => DateTime.Now - PythonInferenceCompleted;

        /// <summary>
        /// Gets the C# processing overhead (time between Python completion and C# reception).
        /// Returns null if ResultReceivedInCSharp is not set.
        /// </summary>
        public TimeSpan? CSharpProcessingOverhead
        {
            get
            {
                if (ResultReceivedInCSharp.HasValue)
                {
                    return ResultReceivedInCSharp.Value - PythonInferenceCompleted;
                }
                return null;
            }
        }

        /// <summary>
        /// Gets the Python execution time as a TimeSpan.
        /// </summary>
        public TimeSpan PythonExecutionTime
        {
            get
            {
                if (PythonInferenceStarted.HasValue)
                {
                    return PythonInferenceCompleted - PythonInferenceStarted.Value;
                }
                return TimeSpan.FromMilliseconds(InferenceTimeMs);
            }
        }

        /// <summary>
        /// Creates a new PredictionTimestamp with the request initiated timestamp set to now.
        /// </summary>
        public static PredictionTimestamp Create(string symbol, string modelType = null, string requestId = null)
        {
            return new PredictionTimestamp
            {
                RequestInitiated = DateTime.Now,
                Symbol = symbol,
                ModelType = modelType,
                RequestId = requestId ?? Guid.NewGuid().ToString()
            };
        }

        /// <summary>
        /// Marks the Python inference as completed with the current timestamp.
        /// </summary>
        public void MarkPythonInferenceCompleted()
        {
            PythonInferenceCompleted = DateTime.Now;
            if (PythonInferenceStarted.HasValue)
            {
                InferenceTimeMs = (PythonInferenceCompleted - PythonInferenceStarted.Value).TotalMilliseconds;
            }
        }

        /// <summary>
        /// Marks the result as received in C# with the current timestamp.
        /// </summary>
        public void MarkResultReceivedInCSharp()
        {
            ResultReceivedInCSharp = DateTime.Now;
            TotalRoundtripTimeMs = (ResultReceivedInCSharp.Value - RequestInitiated).TotalMilliseconds;
        }

        /// <summary>
        /// Returns a summary string of the timing information.
        /// </summary>
        public override string ToString()
        {
            return $"PredictionTimestamp[{Symbol}]: Python={InferenceTimeMs:F2}ms, Roundtrip={TotalRoundtripTimeMs:F2}ms, Age={Age.TotalSeconds:F1}s, Cached={WasCached}";
        }

        /// <summary>
        /// Gets a formatted string for display in UI or logs.
        /// </summary>
        public string GetFormattedSummary()
        {
            var summary = $"Symbol: {Symbol}\n";
            summary += $"Request ID: {RequestId}\n";
            summary += $"Model Type: {ModelType ?? "Unknown"}\n";
            summary += $"Request Initiated: {RequestInitiated:yyyy-MM-dd HH:mm:ss.fff}\n";

            if (PythonInferenceStarted.HasValue)
            {
                summary += $"Python Started: {PythonInferenceStarted:yyyy-MM-dd HH:mm:ss.fff}\n";
            }

            summary += $"Python Completed: {PythonInferenceCompleted:yyyy-MM-dd HH:mm:ss.fff}\n";

            if (ResultReceivedInCSharp.HasValue)
            {
                summary += $"Received in C#: {ResultReceivedInCSharp:yyyy-MM-dd HH:mm:ss.fff}\n";
            }

            summary += $"Inference Time: {InferenceTimeMs:F2}ms\n";
            summary += $"Total Roundtrip: {TotalRoundtripTimeMs:F2}ms\n";

            if (CSharpProcessingOverhead.HasValue)
            {
                summary += $"C# Overhead: {CSharpProcessingOverhead.Value.TotalMilliseconds:F2}ms\n";
            }

            if (WasCached)
            {
                summary += $"Cache Status: Retrieved from cache\n";
                if (RetrievedFromCache.HasValue)
                {
                    summary += $"Retrieved At: {RetrievedFromCache:yyyy-MM-dd HH:mm:ss.fff}\n";
                }
            }
            else
            {
                summary += $"Cache Status: Fresh prediction\n";
            }

            summary += $"Prediction Age: {Age.TotalSeconds:F1}s\n";

            return summary;
        }
    }
}
